FROM python:3.10-slim

# Install system packages
RUN apt-get update && apt-get install -y \
    wkhtmltopdf \
    build-essential \
    libffi-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Set work directory
WORKDIR /app

# Copy project files
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 8000

# Start app with gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:8000", "app:app"]
